version: '3.8'

services:
  db:
    image: prueba_mysql
    container_name: prueba_mysql
    build:
      context: .
      dockerfile: ./mysql_db/Dockerfile
    networks:
      - docker1


  web:
    image: prueba_apache
    container_name: prueba_apache
    build:
      context: .
      dockerfile: ./apache/Dockerfile
    ports:
      - "8085:80"
    volumes:
      - ./apache/files/:/var/www/html
    networks:
      - docker1

networks:
  docker1:
