apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 8085  # Puerto expuesto
      targetPort: 80
  type: NodePort  # Para exponer el servicio fuera del clúster
